/* Generated by AN DISI Unibo */ 
package it.unibo.steprobot

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Steprobot ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("RobotStep: I'm working")
					}
					 transition(edgeName="t00",targetState="handleStep",cond=whenDispatch("step"))
					transition(edgeName="t01",targetState="handleStop",cond=whenDispatch("stop"))
				}	 
				state("handleStep") { //this:State
					action { //it:State
						println("RobotStep: do step")
						forward("cmd", "cmd(w)" ,"basicrobot" ) 
						stateTimer = TimerActor("timer_handleStep", 
							scope, context!!, "local_tout_steprobot_handleStep", 2000.toLong() )
					}
					 transition(edgeName="t12",targetState="handleStop",cond=whenTimeout("local_tout_steprobot_handleStep"))   
					transition(edgeName="t13",targetState="handleStop",cond=whenDispatch("stop"))
				}	 
				state("handleStop") { //this:State
					action { //it:State
						println("RobotStep: stop")
						forward("cmd", "cmd(h)" ,"basicrobot" ) 
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
