/* Generated by AN DISI Unibo */ 
package it.unibo.radar

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Radar ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "init"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("init") { //this:State
					action { //it:State
						radarPojo.radarSupport.setUpRadarGui(  )
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("[Radar] Waiting data...")
					}
					 transition(edgeName="dataReceived0",targetState="updateRadar",cond=whenDispatch("sonar"))
				}	 
				state("updateRadar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("sonar(Distance,Theta)"), Term.createTerm("sonar(Distance,Theta)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								radarPojo.radarSupport.update( payloadArg(0), payloadArg(1)  )
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
